### ISSUE TITLE
Long syntax

### ISSUE THREAD

**Issue by ai** [macropodhq/postcss-constants#3]
Syntax is too long. Why not just `~color.primary`?

**Comment by ojame** [comment]
It was just a personal choice, to play along with the `import {module} from 'path'` syntax and the `composes: Selector from 'path';`.

The difference is, i suppose, the above two examples contain a string path where as `primary from ~color` does not.

Not sure how i feel really!

**Comment by petetnt** [comment]
I agree with @ai here. I really like the concept, but the input syntax is a bit off a turnoff, and I imagine would make the files more convoluted in the long run with hundreds of `x from y` statements floating around.
