### ISSUE TITLE
Nesting in module.exports

### ISSUE THREAD

**Issue by MrFirthy** [macropodhq/postcss-constants#8]
Hi,
Firstly, really useful plugin so thank you.
I was wondering if there is any reason why you can't nest variables in the `module.exports` for use in the CSS. For example if you attempt the following:

```
module.exports = {
    colors: {
        primary: '#8EE7D3',
        secondary: {
            color: '#c70505'
        }
    }
};
```

You cannot then reference `~colors.secondary.color` in the CSS, but you can reference `~colors.primary` as expected.

**Comment by damsorian** [comment]
+1

**Comment by ojame** [comment]
Would you want to nest forever, or is a second level far enough?

**Comment by MrFirthy** [comment]
A second level would be fine for me personally but I'd guess having no limit for nesting would be useful for many.
